# Site settings
title: CarlのBlog                     # 你的博客网站标题
SEOTitle: 武汉同学的博客 | CarlのBlog        # SEO，显示在浏览器上搜索的时候显示的标题
header-img: img/home-bg.jpg        # 显示在首页的背景图片
email: carlsonglin@me.com
description:  "个人学习"              # 网站介绍
keyword: "武汉同学, Carl, Blog, CarlBlog, 数码科技"    # 关键词
url: "https://haijc.cn"           # 这个就是填写你的博客地址
baseurl: ""                 # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
weibo_username:     songlincarl
zhihu_username:     carlsonglin
#github_username:    CarlCit
twitter_username:   carlsonglin



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: carlcit

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-186788750-1'            # Format: UA-xxxxxx-xx
ga_domain: haijc.cn



# Sidebar settings
sidebar: true                           # 是否开启侧边栏
sidebar-about-description: "～努力成长<br>只为更好～"  # 题图简单描述
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # 使用该标签的文章数大于上面设定的条件值，这个标签就会在首页上被推荐。



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
    },{
        title: "乱序",
        href: "http://mida.re/"
    },{
        title: "Sherry Wu",
        href: "https://xuechundesign.github.io"
    }
]
