# Site settings
title: ğŸ“® Carlã®Blog               # ä½ çš„åšå®¢ç½‘ç«™æ ‡é¢˜
SEOTitle: æ­¦æ±‰åŒå­¦ ğŸ“® Carlã®Blog    # SEOï¼Œæ˜¾ç¤ºåœ¨æµè§ˆå™¨ä¸Šæœç´¢çš„æ—¶å€™æ˜¾ç¤ºçš„æ ‡é¢˜
header-img: img/home-bg.jpg        # æ˜¾ç¤ºåœ¨é¦–é¡µçš„èƒŒæ™¯å›¾ç‰‡
email: me@songlin.me
description:  "æ­¦æ±‰åŒå­¦æ˜¯ä¸€ä¸ªå–œæ¬¢æŠ˜è…¾çš„æ•°ç çˆ±å¥½è€…ï¼Œåšå®¢è®°å½•ä¸ªäººå­¦ä¹ ç¬”è®°ï¼ŒæŠ˜è…¾ç»éªŒåˆ†äº«ç­‰ã€‚"     # ç½‘ç«™ä»‹ç»
keyword: "æ­¦æ±‰åŒå­¦,æ­¦æ±‰,åŒå­¦,åšå®¢,Carl,Carlã®Blog,Blog"   # å…³é”®è¯
url: "https://new.songlin.me"                 # è¿™ä¸ªå°±æ˜¯å¡«å†™ä½ çš„åšå®¢åœ°å€
baseurl: "/"                         # ä¾‹å¦‚, '/blog' ä½ çš„åšå®¢ä½äº 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true 
# instagram_username: songlin.me
weibo_username:     songlincarl
# zhihu_username:     carlsonglin
youtube_username:   UCctxtvu9G4AfYFabLWinYDg
# github_username:  CarlCit
twitter_username: carlsonglin



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# disqus_username: carlcit

# Netease settings
# netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'G-TYE2L3CZHS'            # Format: UA-xxxxxx-xx
ga_domain: songlin.me



# Sidebar settings
sidebar: true                           # æ˜¯å¦å¼€å¯ä¾§è¾¹æ 
sidebar-about-description: "ğŸ‘‹ ä¸€ä¸ªå–œæ¬¢æŠ˜è…¾çš„æ•°ç çˆ±å¥½è€…<br>ğŸ˜ ï£¿ äº§å“ ğŸ“± ğŸ’» âŒšï¸ ğŸ–¥ ğŸ§ ğŸ–±<br>ğŸ“Œ æ±‚çŸ¥è‹¥æ¸´ï¼Œè™šå¿ƒè‹¥æ„šã€‚<br>ğŸ“® me@songlin.me"  # é¢˜å›¾ç®€å•æè¿°
sidebar-avatar: /img/avatar.gif      # ä½¿ç”¨ç»å¯¹ URL åœ°å€, å› ä¸ºåŒæ—¶ç”¨äº `/` å’Œ `/about/`



# Featured Tags
featured-tags: true                     # æ˜¯å¦ä½¿ç”¨è¦ç´ æ ‡è®°
featured-condition-size: 3              # ä½¿ç”¨è¯¥æ ‡ç­¾çš„æ–‡ç« æ•°å¤§äºä¸Šé¢è®¾å®šçš„æ¡ä»¶å€¼ï¼Œè¿™ä¸ªæ ‡ç­¾å°±ä¼šåœ¨é¦–é¡µä¸Šè¢«æ¨è



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false


# Friends
friends: [
    {
        title: "Hux Blog",
        href: "https://huangxuan.me"
    },{
        title: "maxOS",
        href: "https://maxoxo.me"
    },{
        title: "Kimen's",
        href: "https://blog.kimen.com.cn"
    },{
        title: "ä¹¦å±±æœ‰è·¯",
        href: "https://sumju.net"
    },{
        title: "é›¨æˆˆæ—å¤š",
        href: "https://moonagic.com"
    },{
        title: "Sleele",
        href: "https://sleele.com"
    },{
        title: "Sukka",
        href: "https://blog.skk.moe"
    },{
        title: "MARKSZ",
        href: "https://molunerfinn.com"
    },{
        title: "Bryce Yang",
        href: "https://todebug.com"
    },{
        title: "æ€æœ‰äº‘",
        href: "https://www.ioiox.com"
    },{
        title: "DIYgod",
        href: "https://diygod.me"
    },{
        title: "OldPanda",
        href: "https://old-panda.com"
    }
]
