# Site settings
title: Carlã®Blog           # ä½ çš„åšå®¢ç½‘ç«™æ ‡é¢˜
SEOTitle: Carlã®Blog        # SEOï¼Œæ˜¾ç¤ºåœ¨æµè§ˆå™¨ä¸Šæœç´¢çš„æ—¶å€™æ˜¾ç¤ºçš„æ ‡é¢˜
header-img: img/home-bg.jpg     # æ˜¾ç¤ºåœ¨é¦–é¡µçš„èƒŒæ™¯å›¾ç‰‡
email: carlsonglin@me.com
description:  "ä¸ªäººå­¦ä¹ ç¬”è®°ï¼Œç»éªŒåˆ†äº«"         # ç½‘ç«™ä»‹ç»
keyword: "æ­¦æ±‰åŒå­¦, Carl, Blog, CarlBlog, æ•°ç ç§‘æŠ€"    # å…³é”®è¯
url: "https://haijc.cn"       # è¿™ä¸ªå°±æ˜¯å¡«å†™ä½ çš„åšå®¢åœ°å€
baseurl: ""        # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true 
instagram_username: carl.songlin
weibo_username:     songlincarl
# zhihu_username:     carlsonglin
youtube_username:   UCctxtvu9G4AfYFabLWinYDg
# github_username:  CarlCit
# twitter_username: carlsonglin



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# disqus_username: carlcit

# Netease settings
# netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-186788750-1'            # Format: UA-xxxxxx-xx
ga_domain: haijc.cn



# Sidebar settings
sidebar: true                           # æ˜¯å¦å¼€å¯ä¾§è¾¹æ 
sidebar-about-description: "ğŸ‘‹ ä¸€ä¸ªå–œæ¬¢æŠ˜è…¾çš„æ•°ç çˆ±å¥½è€…<br>ğŸ˜ ï£¿ äº§å“ ğŸ“± ğŸ’» âŒšï¸ ğŸ–¥ âŒ¨ï¸ ğŸ–±<br>ğŸ“Œ æ±‚çŸ¥è‹¥æ¸´ï¼Œè™šå¿ƒè‹¥æ„šã€‚<br>ğŸ“® haijc#qq.com  #->@"  # é¢˜å›¾ç®€å•æè¿°
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # ä½¿ç”¨è¯¥æ ‡ç­¾çš„æ–‡ç« æ•°å¤§äºä¸Šé¢è®¾å®šçš„æ¡ä»¶å€¼ï¼Œè¿™ä¸ªæ ‡ç­¾å°±ä¼šåœ¨é¦–é¡µä¸Šè¢«æ¨èã€‚



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: fslse


# Friends
friends: [
    {
        title: "Hux Blog",
        href: "https://huangxuan.me"
    },{
        title: "Sherry Woo",
        href: "https://sherrywoo.me"
    },{
        title: "é›¨æˆˆæ—å¤š",
        href: "https://moonagic.com"
    },{
        title: "Sleele",
        href: "https://sleele.com"
    },{
        title: "Sukka",
        href: "https://blog.skk.moe"
    },{
        title: "MARKSZ",
        href: "https://molunerfinn.com"
    },{
        title: "Bryce Yang",
        href: "https://todebug.com"
    },{
        title: "æ€æœ‰äº‘",
        href: "https://www.ioiox.com"
    },{
        title: "DIYgod",
        href: "https://diygod.me"
    },{
        title: "OldPanda",
        href: "https://old-panda.com"
    }
]
